on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - id: changed-dirs
      uses: tj-actions/changed-files@v24.1
      with:
        dir_names: "true"

    - id: env
      run: |
        dir=$(for d in ${{ steps.changed-dirs.outputs.all_changed_files }}; do echo "${d}"; done)
        echo $dir
        dir=dev
        echo "::set-output name=env::$(echo $dir)"

  plan:
    needs: prepare
    runs-on: ubuntu-latest
    environment: ${{ needs.prepare.outputs.env}}.plan
    steps:
    - run: |
        echo "${{ needs.prepare.outputs.env }}"
        echo "name=${{ inputs.name }}"
        echo "TFE_ORG=${{ secrets.TFE_ORG }}"
