on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      GRADES: ${{ secrets.GRADES }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - id: validate
      name: terraform validate
      uses: LeiZhaoGFT/reusable-workflow/.github/actions/terraform-validate@main
      with:
        REPO_SECRET: ${{ secrets.GRADES }} 
        PWD: dev

    # - id: changed-dirs
    #   uses: tj-actions/changed-files@v24.1
    #   with:
    #     dir_names: "true"

    - id: matrix
      name: matrix
      run: |
        if ${{ github.event_name == 'workflow_dispatch' }}
        then
          matrix='{"env":["dev"]}'
          echo "::set-output name=matrix::$matrix"
        elif ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        then
          environments=$(for grade in $GRADES; do if ! git diff --quiet HEAD main -- $grade; then echo $grade; fi; done)
          echo $environments
          echo "::set-output name=environments::$(echo $environments)"
        fi

  plan:
    needs: prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}.plan
    steps:
    - run: |
        echo "env=${{ matrix.env }}"
        echo "name=${{ inputs.name }}"
        echo "TFE_ORG=${{ secrets.TFE_ORG }}"
