on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      env:
        required: true
        type: string  

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env}}.plan
    steps:
      - run: |
          echo "name=${{ inputs.name }}"
          echo "TFE_ORG=${{ secrets.TFE_ORG }}"
