name: 'terraform validate'
description: 'Terrform Validate'

inputs:
  ORG_SECRET:  
    description: 'TFE_ORG secret'
    required: true
  PWD:
    description: 'working directory'
    required: true

runs:
  using: "composite"
  steps:
  - id: working_dir
    run: |
      pwd
      ls -a
    shell: bash  
    working-directory: ${{ inputs.PWD }}

  - id: secret_input
    run: echo "TFE_ORG=${{ inputs.ORG_SECRET }}"
    shell: bash
    working-directory: ${{ inputs.PWD }}
